import {travelData as d} from './data/travel.js';
import {formatMoney as money,localTime} from './engine.js';
export const componentNames=['Business context','Ontology','Disambiguation','Metrics','Relationships','Verified examples'];
export const eventNames=['Input received','Meaning applied','Tool requested','Evidence returned'];
export function buildComponents(plan,question) {
  const o=plan.options,p=plan.selected,quiet=o.memory&&o.priority!=='cheapest';
  const preference=o.priority==='cheapest'?'Lowest complete price overrides the quiet-hotel preference.':o.priority==='earliest'?(o.memory?'Earliest venue arrival comes first; remembered hotel preferences break ties.':'Earliest venue arrival comes first. Memory is paused.'):o.memory?'Quiet hotel, within walking distance.':'Memory is paused; use the current request only.';
  return [
    {inputLabel:'“Get me to my meeting”',mapping:'Arrive at the venue by 14:00',service:'Amazon Bedrock · agent application on AgentCore Runtime',intro:'Translate a travel request into the outcome that actually matters.',input:question,rule:'The business objective is timely arrival at the meeting venue. A flight landing before 14:00 is only one leg of that objective.',tool:'resolve_trip_objective',args:{trip_id:d.trip.id,request:question},output:{goal:'reach meeting venue',deadline:d.trip.deadline,scope:d.trip.scope},source:'Prepared trip policy · trip-policy-v1',brief:['Goal','Reach Ribeira Design Studio by 14:00.']},
    {inputLabel:'“Heathrow”, “Lisbon”, “my meeting”',mapping:'LHR → LIS → venue-ribeira',service:'Aurora PostgreSQL · shared entity registry',intro:'Connect different names to the same traveller, airports and destination.',input:{traveller:'Alex Morgan',origin:'Heathrow',destination:'Lisbon',meeting:'Ribeira Design Studio'},rule:'Use stable entity IDs across supplier offers, airport records, venue transfers, hotel walks and user context.',tool:'resolve_trip_entities',args:{actor_id:d.traveller.actorId,trip_id:d.trip.id},output:{traveller_id:d.traveller.id,origin:'LHR',destination:'LIS',venue_id:d.venue.id,hotel_nights:1,checked_bags:1},source:'Prepared traveller, airport and venue records · onward-demo-v1',brief:['Entities','Alex · LHR → LIS · Ribeira Design Studio']},
    {inputLabel:quiet?'“tomorrow”, “nearby” + remembered “quiet”':'“tomorrow”, “nearby” + today’s priority',mapping:`15 Sep · within 20 min on foot${o.priority==='earliest'?' · earliest venue arrival':quiet?' · quiet hotels':o.priority==='cheapest'?' · lowest complete price':' · current request'}`,service:'AgentCore Memory + Aurora text / pgvector retrieval',intro:'Resolve ambiguous language and retrieve relevant options with personal context.',input:{demo_clock:d.demoClock,prior_conversation:o.memory?d.memory.quote:'Memory paused',current_priority:o.priority},rule:'“Tomorrow” uses the London demo clock; arrival uses the venue’s Lisbon time zone. The prepared trip policy defines nearby as ≤20 minutes on foot. Text/vector retrieval can connect quiet with courtyard-facing rooms. Relevance does not establish feasibility.',tool:'retrieve_travel_context_and_candidates',args:{actor_id:d.traveller.actorId,memory_enabled:o.memory,travel_date:d.travelDate,hotel_query:quiet?'quiet, walkable hotel':'hotel near meeting venue'},output:{date:d.travelDate,timezones:['Europe/London','Europe/Lisbon','Europe/Madrid'],preference,flight_offer_ids:d.offers.map(f=>f.id),hotel_ids:d.hotels.map(h=>h.id)},source:'Seeded actor-scoped memory + authored retrieval candidates; no vectors or similarity scores computed',brief:['Meaning',`15 September · hotel ≤20 min walk. ${preference}`]},
    {inputLabel:`“Under ${money(o.budgetPence)}”`,mapping:'Fare + bag + hotel taxes + airport transfer',service:'Shared business metric · Aurora SQL contract',intro:'Give “total trip cost” one complete, consistent definition.',input:{budget_pence:o.budgetPence,hotel_nights:1,checked_bag_kg:23,currency:'GBP'},rule:'Use integer pence. Sum outbound fare + one 23kg bag + one tax-inclusive hotel night + the airport-to-venue transfer. Supplier prices include taxes; do not add them again. “Under” is a strict less-than comparison.',tool:'resolve_complete_trip_cost',args:{metric:'outbound_trip_total',budget_pence:o.budgetPence},output:{formula:'fare + checked_bag + hotel_one_night + airport_to_venue_transfer',taxes:'included in supplier prices',operator:'<',return_flight:'excluded from stated scope'},source:'Prepared metric and scope · trip-policy-v1',brief:['Budget',`All four cost lines, including taxes, under ${money(o.budgetPence)}.`]},
    {inputLabel:'“Will this journey actually work?”',mapping:'13:20 landing → 14:40 at the meeting: rejected',service:'Neptune relationships · application feasibility rules · S3 sources',intro:'Follow the complete journey and reject options that cannot meet the goal.',input:{arrival_allowance_minutes:45,transfer_minutes:35,minimum_connection_minutes:60,hotel_walk_limit_minutes:20},rule:'Expand flight legs, airport arrival allowance, venue transfer and hotel walk. Apply versioned connection and deadline rules over timezone-aware timestamps. A graph stores the relationships; application rules validate the route.',tool:'validate_complete_journeys',args:{candidate_offer_ids:d.offers.map(f=>f.id),venue_id:d.venue.id,deadline:d.trip.deadline},output:{routes:plan.routes.map(r=>({offer:r.offer.id,landing:localTime(r.landing),at_meeting:localTime(r.venueArrival),feasible:r.feasible,reasons:r.reasons})),hotel_exclusion:'Coast Retreat: 55-minute walk exceeds the 20-minute limit'},source:'arrival-policy-v1 · connection-policy-v1 · transfer-LIS-RIB-v1. Optional S3 Vectors retrieves supporting policy passages; it does not decide feasibility.',brief:['Feasibility','Cheap AX404 arrives too late. ME615 has a 45-minute connection. Coast Retreat is too far away.']},
    {inputLabel:'“Which complete trip should I choose?”',mapping:p?`${p.route.offer.id} + ${p.hotel.name} · ${money(p.totalPence)}`:'No complete itinerary meets every constraint',service:'Reviewed tool-use pattern · Aurora SQL · Bedrock response',intro:'Use a consistent query pattern, check current facts, then rank eligible bundles.',input:{budget:money(o.budgetPence),current_priority:o.priority,memory_enabled:o.memory},rule:'A reviewed example guides bounded tool calls. Current offer records establish prices and availability. Filter every hard constraint before ranking by today’s priority and remembered preferences. Return no match when no bundle qualifies.',tool:'check_offers_and_rank_itineraries',args:{example_id:'reviewed-example-v1',travel_date:d.travelDate,budget_pence:o.budgetPence,availability_snapshot:d.snapshot,priority:o.priority},output:{eligible_bundles:plan.eligible.length,selected:p?{flight:p.route.offer.id,hotel:p.hotel.name,total_pence:p.totalPence,meeting_arrival:localTime(p.route.venueArrival)}:null,decision:p?'Supported sample itinerary':'No feasible itinerary within this budget'},source:'Authored example reviewed-example-v1 + fictional offer snapshot. The example is not a production-verified query or proof of current availability.',brief:['Decision',p?`${p.route.offer.id} · ${p.hotel.name} · ${money(p.totalPence)} · at meeting ${localTime(p.route.venueArrival)}`:'No match. Keep the deadline; revisit the budget explicitly.']}
  ];
}
